name: ci-net-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet_versions: [ '6.0.400', '6.0.303' ]
    steps:
      - name: Download
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{matrix.dotnet_versions}}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
