name: ci-net-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet_versions: [ '3.1.x', '5.0.x', '6.0.x' ]
    steps:
      - name: Download
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{matrix.dotnet_versions}}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
