name: ci-net-workflow
on: [push]
jobs:
  check-application-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
